name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js '18.x'
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Build
      run: |
        npm install
        npm run dev
